<?php /** @var \Lib\View\Renderer\PhpRendererInterface $this */?>
<?php $this->declareVars("text", ["ico" => "cogs"]); ?>
<div class="x_title">
    <h2><?php echo $this->translate($this->text); ?><small>Click to validate</small></h2>
    <ul class="nav navbar-right panel_toolbox">
        <li>
            <a class="collapse-link">
                <i class="fa fa-chevron-up"></i>
            </a>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                <i class="fa fa-wrench"></i>
            </a>
            <ul class="dropdown-menu" role="menu">
                <li><a href="#">Settings 1</a></li>
                <li><a href="#">Settings 2</a></li>
            </ul>
        </li>
        <li>
            <a class="close-link">
                <i class="fa fa-close"></i>
            </a>
        </li>
    </ul>
    <div class="clearfix"></div>
</div>