<?php echo $this->doctype(); ?>
<html lang="en">
  <head>
      <?php echo $this->headTitle('Admin Interface')->setSeparator(' - ')->setAutoEscape(false) ?>
      <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')
          ->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>

      <!-- Le styles -->
      <?php echo $this->headLink()->prependStylesheet('/dashboard/css/custom.min.css')
          ->prependStylesheet('/dashboard/vendors/bootstrap-daterangepicker/daterangepicker.css')
          ->prependStylesheet('/dashboard/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css')
          ->prependStylesheet('/dashboard/vendors/nprogress/nprogress.css')
          ->prependStylesheet('/dashboard/vendors/font-awesome/css/font-awesome.min.css')
          ->prependStylesheet('/dashboard/vendors/bootstrap/dist/css/bootstrap.min.css');?>

      <!-- Scripts -->
      <?php $this->headScript()->prependFile('/dashboard/vendors/fastclick/lib/fastclick.js', 'text/javascript')
          ->prependFile('/dashboard/vendors/nprogress/nprogress.js', 'text/javascript')
          ->prependFile('/dashboard/vendors/bootstrap/dist/js/bootstrap.min.js', 'text/javascript')
          ->prependFile('/dashboard/vendors/jquery/dist/jquery.min.js', 'text/javascript')
          ->appendFile('/dashboard/js/custom.min.js', 'text/javascript'); ?>
    </head>

    <body class="nav-md">

        <div class="container body">
            <div class="main_container">

                <div class="col-md-3 left_col">
                    <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="<?php echo $this->url('zfcadmin'); ?>" class="site_title">
                            <i class="fa fa-paw"></i>
                            <span><?php echo $this->translate('Dashboard'); ?></span>
                        </a>
                    </div>

                    <div class="clearfix"></div>

                    <!-- menu profile quick info -->
                    <div class="profile">
                      <div class="profile_pic">
                        <img src="/dashboard/img/img.jpg" alt="..." class="img-circle profile_img">
                      </div>
                      <div class="profile_info">
                        <span><?php echo $this->translate('Welcome'); ?>,</span>
                        <h2><?php echo $this->identity()->getDisplayName()?></h2>
                      </div>
                    </div>
                    <!-- /menu profile quick info -->

                    <br />

                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <h3>Menu</h3>
                            <?php echo $this->navigation('admin_navigation')->menu()
                                ->setPartial('dashboard/partial/menu')->render(); ?>
                        </div>
                    </div>
                    <!-- /sidebar menu -->

                    <!-- /menu footer buttons -->
                    <div class="sidebar-footer hidden-small">
                      <a data-toggle="tooltip" data-placement="top" title="Settings">
                        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                      </a>
                      <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                      </a>
                      <a data-toggle="tooltip" data-placement="top" title="Lock">
                        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                      </a>
                      <a data-toggle="tooltip" data-placement="top" title="Logout" href="<?php echo $this->url('zfcuser/logout'); ?>">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                      </a>
                    </div>
                    <!-- /menu footer buttons -->
                  </div>
                </div>

                <!-- top navigation -->
                <div class="top_nav">
                    <div class="nav_menu">
                        <nav>
                            <div class="nav toggle">
                                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                            </div>
                            <ul class="nav navbar-nav navbar-right">
                                <li class="">
                                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                        <img src="/dashboard/images/img.jpg" alt="">
                                        <?php echo $this->identity()->getDisplayName();?>
                                        <span class=" fa fa-angle-down"></span>
                                    </a>
                                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                                        <li>
                                            <a href="javascript:;">
                                                <?php echo $this->translate('Profile'); ?>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="javascript:;">
                                                <span class="badge bg-red pull-right">50%</span>
                                                <span><?php echo $this->translate('Settings'); ?></span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="javascript:;">
                                                <?php echo $this->translate('Help'); ?>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="<?php echo $this->url('zfcuser/logout'); ?>">
                                                <i class="fa fa-sign-out pull-right"></i>
                                                <?php echo $this->translate('Log Out'); ?>
                                            </a>
                                        </li>
                                    </ul>
                                </li>

                                <li role="presentation" class="dropdown">
                                    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                                        <i class="fa fa-envelope-o"></i>
                                        <span class="badge bg-green">6</span>
                                    </a>
                                    <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                                        <li>
                                            <a>
                                                <span class="image"><img src="/dashboard/images/img.jpg" alt="Profile Image" /></span>
                                                <span>
                                                    <span>John Smith</span>
                                                    <span class="time">3 mins ago</span>
                                                </span>
                                                <span class="message">
                                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                                </span>
                                            </a>
                                        </li>
                                        <li>
                                            <a>
                                                <span class="image">
                                                    <img src="/dashboard/images/img.jpg" alt="Profile Image" />
                                                </span>
                                                <span>
                                                    <span>John Smith</span>
                                                    <span class="time">3 mins ago</span>
                                                </span>
                                                <span class="message">
                                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                                </span>
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </nav>
                    </div>
<!--                    <ol class="breadcrumb">-->
<!--                        <li>-->
<!--                            --><?php //echo $this->navigation('admin_navigation')
//                                ->breadcrumbs()->setSeparator('</li><li>'); ?>
<!--                        </li>-->
<!--                    </ol>-->
                </div>
                <!-- /top navigation -->

                <!-- page content -->
                <div class="right_col" role="main">
                    <?php echo $this->content; ?>
                </div>
                <!-- /page content -->

                <!-- footer content -->
                <footer>
                    <div class="pull-right">
                        Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
                    </div>
                    <div class="clearfix"></div>
                </footer>
                <!-- /footer content -->
            </div>
        </div>

        <?php echo $this->headScript(); ?>

        <?php echo $this->inlineScript(); ?>
    </body>
</html>